# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
name: native app workflow using ImageRunner

on:
  workflow_dispatch:

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  run-appium-sauce:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          working-directory: "./"


