apiVersion: v1alpha
kind: imagerunner
sauce:
  region: eu-central-1
suites:
  - name: Hosted Test Orchestration Demo
    workload: webdriver
    image: eyalyovelsauce/sauce-java-appium-cross-platform-docker:latest
    entrypoint: mvn clean install
#    imagePullAuth:
#      user: $DOCKER_USERNAME
#      token: $DOCKER_PASSWORD
